import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/navbar/page";
import Footer from "./_component/footer/page";
import { Toaster } from "@/components/ui/sonner"
import CartContextProvider from "./_component/context/cartContext";
import MyUseSession from "./_component/MyUseSession/MyUseSession";
import { getToken } from "./Helpers/getUserToken";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "shop mart",
  description: "Generated by create next app",
};
const userToken = await getToken()
export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <MyUseSession>
          <CartContextProvider userToken={userToken!}>
          <Navbar/>
        <div className="container mx-auto">
        {children}
        <Toaster />
        <Footer/>
        </div>
        </CartContextProvider>
        </MyUseSession>
      </body>
    </html>
  );
}
//ahmedmuttii4012@gmail.com